import type { Metadata } from "next";
import "/src/styles/globals.css";
import { Jost } from "next/font/google";

const jost = Jost({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${jost.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
